export const ProgressTypes = {
  SAVE_PROGRESS: "SAVE_PROGRESS",
  SET_PERCENT: "SET_PERCENT",
  SET_DISABLED: "SET_DISABLED",
  SET_IS_SHOW_PROGRESS_BAR: "SET_IS_SHOW_PROGRESS_BAR",
  SET_TEXT_BUTTON_PROGRESS: "SET_TEXT_BUTTON_PROGRESS",
  SET_AMOUNT_PERCENT_INCREAMENT: "SET_AMOUNT_PERCENT_INCREAMENT",
};

export const SizeBrowser = {
  SET_SIZE_BROWSER: "SET_SIZE_BROWSER",
};

export const StartYourWill = {
  SET_NAME: "SET_NAME",
  SET_MAKE_PAYMENT: "SET_MAKE_PAYMENT",
};
