export const ProgressTypes = {
  SAVE_PROGRESS: "SAVE_PROGRESS",
  SET_PERCENT: "SET_PERCENT",
  SET_DISABLED: "SET_DISABLED",
  SET_IS_SHOW_PROGRESS_BAR: "SET_IS_SHOW_PROGRESS_BAR",
  SET_TEXT_BUTTON_PROGRESS: "SET_TEXT_BUTTON_PROGRESS",
  SET_AMOUNT_PERCENT_INCREAMENT: "SET_AMOUNT_PERCENT_INCREAMENT",
  SET_PUSHABLE: "SET_PUSHABLE",
  SET_ROUTER: "SET_ROUTER",
};

export const SizeBrowser = {
  SET_SIZE_BROWSER: "SET_SIZE_BROWSER",
};

export const StartYourWill = {
  SET_NAME: "SET_NAME",
  SET_MAKE_PAYMENT: "SET_MAKE_PAYMENT",
};

export const PersonalEstatesListingTypes = {
  SET_PROPERTY: "SET_PROPERTY",
  SET_PERSONAL_INFORMATION: "SET_PERSONAL_INFORMATION",
  SET_EXECUTOR: "SET_EXECUTOR",
  SET_BENEFICIARY: "SET_BENEFICIARY",
}

export const MasterDataTypes = {
  GET_MASTER_DATA: "GET_MASTER_DATA",
  SAVE_MASTER_DATA: "SAVE_MASTER_DATA",
}


export const CategoryTypes = {
  GET_CATEGORY_DATA: "GET_CATEGORY_DATA",
  SAVE_CATEGORY_DATA: "SAVE_CATEGORY_DATA",
}